### ISSUE TITLE
Why insert rectangles?

### ISSUE THREAD

**Issue by lonnietc** [s0rg/quadtree#6]
Hello,

I am reading up on your quadtree implementation and it seems that you are inserting rectangles at different quadtree locations.

I am wondering why rectangles instead of datapoint values or a structure of data instead.

Any clarification would be appreciated.
Thanks

**Comment by s0rg** [comment]
Hello.

I think rectangles are more flexible way to represent areas of any kind, its up to you to decide how large you actual point is. For example you can use `t.Add(x, y, 1.0, 1.0, "some val")` for basic precision, or `t.Add(x, y, 0.1, 0.1, "other val")` for better precision.
